trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # ----- CHANGE THESE IF NEEDED -----
  azureServiceConnection: 'My-Azure-RM'
  resourceGroup: 'my-rg'
  webAppName: 'MyHome'
  nodeVersion: '20.x'
  artifactZip: 'app.zip'

steps:
# ---------- Node + deps ----------
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

# Ensure jest-junit is available so tests show in the Tests tab
- script: npm install --no-save jest-junit
  displayName: 'Install jest-junit reporter'

# ---------- Tests (publish to Azure DevOps) ----------
- script: |
    mkdir -p $(Build.SourcesDirectory)/test-results
    export JEST_JUNIT_OUTPUT=$(Build.SourcesDirectory)/test-results/junit.xml
    npx jest --ci --reporters=default --reporters=jest-junit
  displayName: 'Run unit tests (Jest → JUnit)'

# ---------- Tests & Database Setup ----------
- script: |
    mkdir -p $(Build.SourcesDirectory)/test-results
    # Initialize test database
    node scripts/seed.js
    # Run tests with initialized DB
    export JEST_JUNIT_OUTPUT=$(Build.SourcesDirectory)/test-results/junit.xml
    npx jest --ci --reporters=default --reporters=jest-junit
  displayName: 'Setup DB and Run Tests'
  continueOnError: false

# ---------- Package for deploy (lean zip; exclude node_modules/tests/etc.) ----------
# Stage only deployable files into a temp folder
- task: CopyFiles@2
  displayName: 'Stage deployable files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*
      !.git/**
      !.github/**
      !node_modules/**
      !coverage/**
      !test/**
      !**/*.test.*
      !**/*.spec.*
      scripts/seed.js
      database.js
    TargetFolder: '$(Build.ArtifactStagingDirectory)/package'

# Zip the staged folder
- task: ArchiveFiles@2
  displayName: 'Create deployment zip'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/package'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactZip)'
    replaceExistingArchive: true

# ---------- Configure App Service build settings (Oryx) ----------
# Ensures Azure builds your Node app on deploy and uses Node 20
- task: AzureCLI@2
  displayName: 'Configure App Service build settings'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az webapp config appsettings set \
        --resource-group "$(resourceGroup)" \
        --name "$(webAppName)" \
        --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true WEBSITE_NODE_DEFAULT_VERSION=$(nodeVersion)
  condition: succeeded()   # only if earlier steps (incl. tests) succeeded

# ---------- Deploy to Azure App Service ----------
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service (Linux)'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appType: 'webAppLinux'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/$(artifactZip)'
  condition: succeeded()   # deploy only if tests passed

# Add database initialization after deployment
- task: AzureCLI@2
  displayName: 'Initialize Production Database'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Initializing database..."
      az webapp ssh --resource-group "$(resourceGroup)" --name "$(webAppName)" --command "cd /home/site/wwwroot && node scripts/seed.js" || {
        echo "Database initialization failed"
        exit 1
      }
  condition: succeeded()