// backend/seed_listings.js
const db = require("../database");


// ---- Your base rows (status,address,suburb,postcode,state,price,bed,bath,car,type,image,images[])
const baseRows = [
  // --- Rent ---
  [
    "rent",
    "101 Bridge St",
    "Ultimo",
    "2007",
    "NSW",
    700,
    2,
    1,
    1,
    "Apartment",
    "/Assets/ultimo/ultimo1.webp",
    ["/Assets/ultimo/ultimo2.avif", "/Assets/ultimo/ultimo3.avif"],
  ],
  [
    "rent",
    "12 Ebsworth St",
    "Zetland",
    "2011",
    "NSW",
    820,
    2,
    2,
    1,
    "Apartment",
    "/Assets/zetland/zetland1.webp",
    ["/Assets/zetland/zetland2.avif", "/Assets/zetland/zetland3.avif"],
  ],
  [
    "rent",
    "13 James St",
    "Kingsford",
    "2018",
    "NSW",
    420,
    1,
    1,
    0,
    "House",
    "/Assets/kingsford/kingsford1.webp",
    ["/Assets/kingsford/kingsford2.avif", "/Assets/kingsford/kingsford3.avif"],
  ],
  [
    "rent",
    "7 Harris St",
    "Ultimo",
    "2007",
    "NSW",
    370,
    4,
    2,
    2,
    "Apartment",
    "/Assets/ultimo/ultimo4.webp",
    ["/Assets/ultimo/ultimo5.avif", "/Assets/ultimo/ultimo3.avif"],
  ],
  [
    "rent",
    "15 Viet St",
    "Bankstown",
    "2200",
    "NSW",
    330,
    1,
    1,
    1,
    "House",
    "/Assets/bankstown/bankstown1.webp",
    ["/Assets/bankstown/bankstown2.avif", "/Assets/bankstown/bankstown3.webp"],
  ],
  [
    "rent",
    "22 Charles St",
    "Chippendale",
    "2008",
    "NSW",
    800,
    1,
    1,
    1,
    "Apartment",
    "/Assets/chippendale/chippendale1.webp",
    ["/Assets/chippendale/chippendale2.avif", "/Assets/chippendale/chippendale3.avif"],
  ],
  [
    "rent",
    "1 Harris St",
    "Ultimo",
    "2017",
    "NSW",
    540,
    1,
    1,
    1,
    "Apartment",
    "/Assets/ultimo/ultimo7.webp",
    ["/Assets/ultimo/ultimo8.avif", "/Assets/ultimo/ultimo9.avif"],
  ],
  [
    "rent",
    "21 Ebsworth St",
    "Zetland",
    "2017",
    "NSW",
    930,
    3,
    1,
    1,
    "House",
    "/Assets/zetland/zetland4.webp",
    ["/Assets/zetland/zetland5.avif", "/Assets/zetland/zetland6.avif"],
  ],
  [
    "rent",
    "27 George St",
    "Parramatta",
    "2150",
    "NSW",
    620,
    2,
    2,
    1,
    "Apartment",
    "/Assets/parramatta/parramatta4.webp",
    ["/Assets/parramatta/parramatta5.avif", "/Assets/parramatta/parramatta6.jpg"],
  ],
  [
    "rent",
    "67 Gardeners Rd",
    "Mascot",
    "2020",
    "NSW",
    850,
    4,
    2,
    2,
    "House",
    "/Assets/mascot/mascot1.webp",
    ["/Assets/mascot/mascot2.avif", "/Assets/mascot/mascot3.avif"],
  ],
  [
    "rent",
    "44 Regent St",
    "Chippendale",
    "2008",
    "NSW",
    750,
    3,
    2,
    1,
    "House",
    "/Assets/chippendale/chippendale4.webp",
    ["/Assets/chippendale/chippendale5.avif", "/Assets/chippendale/chippendale6.webp"],
  ],
  [
    "rent",
    "10 Pitt St",
    "Sydney",
    "2000",
    "NSW",
    690,
    2,
    1,
    1,
    "Unit",
    "/Assets/sydney/sydney1.webp",
    ["/Assets/sydney/sydney2.avif", "/Assets/sydney/sydney3.avif"],
  ],
  [
    "rent",
    "85 George St",
    "The Rocks",
    "2000",
    "NSW",
    720,
    1,
    1,
    0,
    "Apartment",
    "/Assets/therock/therock1.webp",
    ["/Assets/therock/therock2.avif", "/Assets/therock/therock3.webp"],
  ],
  [
    "rent",
    "18 Bay St",
    "Glebe",
    "2037",
    "NSW",
    640,
    2,
    1,
    0,
    "Townhouse",
    "/Assets/glebe/glebe1.webp",
    ["/Assets/glebe/glebe2.avif", "/Assets/glebe/glebe3.avif"],
  ],
  [
    "rent",
    "99 King St",
    "Newtown",
    "2042",
    "NSW",
    880,
    3,
    2,
    1,
    "Terrace",
    "/Assets/newtown/newtown1.webp",
    ["/Assets/newtown/newtown2.avif", "/Assets/newtown/newtown3.avif"],
  ],
  [
    "rent",
    "55 Oxford St",
    "Paddington",
    "2021",
    "NSW",
    950,
    3,
    2,
    1,
    "House",
    "/Assets/paddington/paddington1.webp",
    ["/Assets/paddington/paddington2.avif", "/Assets/paddington/paddington3.avif"],
  ],
  [
    "rent",
    "14 Smith St",
    "Parramatta",
    "2150",
    "NSW",
    600,
    2,
    1,
    1,
    "Apartment",
    "/Assets/parramatta/parramatta1.webp",
    ["/Assets/parramatta/parramatta2.avif", "/Assets/parramatta/parramatta3.webp"],
  ],
  [
    "rent",
    "3 Queen St",
    "Ashfield",
    "2131",
    "NSW",
    520,
    2,
    1,
    0,
    "Unit",
    "/Assets/ashfield/ashfield1.webp",
    ["/Assets/ashfield/ashfield2.avif", "/Assets/ashfield/ashfield3.avif"],
  ],
  [
    "rent",
    "200 Church St",
    "Ryde",
    "2112",
    "NSW",
    770,
    3,
    1,
    1,
    "House",
    "/Assets/ryde/ryde1.webp",
    ["/Assets/ryde/ryde2.avif", "/Assets/ryde/ryde3.avif"],
  ],
  [
    "rent",
    "76 Princes Hwy",
    "Kogarah",
    "2217",
    "NSW",
    830,
    3,
    2,
    1,
    "House",
    "/Assets/kogarah/kogarah1.webp",
    ["/Assets/kogarah/kogarah2.avif", "/Assets/kogarah/kogarah3.avif"],
  ],

  // --- Buy ---
  [
    "buy",
    "16 Charlotte St",
    "Chippendale",
    "2000",
    "NSW",
    960000,
    4,
    2,
    2,
    "Apartment",
    "/Assets/parramatta/parramatta1.webp",
    ["/Assets/parramatta/parramatta2.avif", "/Assets/parramatta/parramatta3.webp"],
  ],
  [
    "buy",
    "13 Pitt St",
    "Sydney",
    "2000",
    "NSW",
    873000,
    4,
    2,
    1,
    "House",
    "/Assets/ashfield/ashfield1.webp",
    ["/Assets/ashfield/ashfield2.avif", "/Assets/ashfield/ashfield3.avif"],
  ],
  [
    "buy",
    "45 Quay St",
    "Pyrmont",
    "2009",
    "NSW",
    930000,
    3,
    1,
    1,
    "House",
    "/Assets/kogarah/kogarah1.webp",
    ["/Assets/kogarah/kogarah2.avif", "/Assets/kogarah/kogarah3.avif"],
  ],
  [
    "buy",
    "18 Oxford St",
    "Paddington",
    "2021",
    "NSW",
    1250000,
    3,
    2,
    1,
    "House",
    "/Assets/ryde/ryde1.webp",
    ["/Assets/ryde/ryde2.avif", "/Assets/ryde/ryde3.avif"],
  ],
  [
    "buy",
    "30 Church St",
    "Ryde",
    "2112",
    "NSW",
    1100000,
    4,
    2,
    2,
    "House",
    "/Assets/ryde/ryde1.webp",
    ["/Assets/ryde/ryde2.avif", "/Assets/ryde/ryde3.avif"],
  ],
  [
    "buy",
    "61 Campbell St",
    "Surry Hills",
    "2010",
    "NSW",
    1340000,
    3,
    2,
    1,
    "Townhouse",
    "/Assets/parramatta/parramatta1.webp",
    ["/Assets/parramatta/parramatta2.avif", "/Assets/parramatta/parramatta3.webp"],
  ],
  [
    "buy",
    "77 Victoria Rd",
    "Gladesville",
    "2111",
    "NSW",
    980000,
    3,
    2,
    1,
    "House",
    "/Assets/ashfield/ashfield1.webp",
    ["/Assets/ashfield/ashfield2.avif", "/Assets/ashfield/ashfield3.avif"],
  ],
  [
    "buy",
    "8 Princes Hwy",
    "Kogarah",
    "2217",
    "NSW",
    1050000,
    4,
    2,
    2,
    "House",
    "/Assets/kogarah/kogarah1.webp",
    ["/Assets/kogarah/kogarah2.avif", "/Assets/kogarah/kogarah3.avif"],
  ],
  [
    "buy",
    "25 George St",
    "Burwood",
    "2134",
    "NSW",
    870000,
    2,
    1,
    1,
    "Apartment",
    "/Assets/ryde/ryde1.webp",
    ["/Assets/ryde/ryde2.avif", "/Assets/ryde/ryde3.avif"],
  ],
  [
    "buy",
    "3 Charles St",
    "Liverpool",
    "2170",
    "NSW",
    950000,
    3,
    2,
    1,
    "House",
    "/Assets/parramatta/parramatta1.webp",
    ["/Assets/parramatta/parramatta2.avif", "/Assets/parramatta/parramatta3.webp"],
  ],
  [
    "buy",
    "77 Bay St",
    "Glebe",
    "2037",
    "NSW",
    1220000,
    3,
    2,
    2,
    "House",
    "/Assets/ashfield/ashfield1.webp",
    ["/Assets/ashfield/ashfield2.avif", "/Assets/ashfield/ashfield3.avif"],
  ],
  [
    "buy",
    "100 Regent St",
    "Chippendale",
    "2008",
    "NSW",
    1180000,
    3,
    2,
    1,
    "Terrace",
    "/Assets/kogarah/kogarah1.webp",
    ["/Assets/kogarah/kogarah2.avif", "/Assets/kogarah/kogarah3.avif"],
  ],
  [
    "buy",
    "42 King St",
    "Newtown",
    "2042",
    "NSW",
    890000,
    2,
    1,
    1,
    "Apartment",
    "/Assets/ryde/ryde1.webp",
    ["/Assets/ryde/ryde2.avif", "/Assets/ryde/ryde3.avif"],
  ],
  [
    "buy",
    "90 Oxford St",
    "Bondi Junction",
    "2022",
    "NSW",
    1350000,
    3,
    2,
    1,
    "House",
    "/Assets/parramatta/parramatta1.webp",
    ["/Assets/parramatta/parramatta2.avif", "/Assets/parramatta/parramatta3.webp"],
  ],
  [
    "buy",
    "3 Marrickville Rd",
    "Marrickville",
    "2204",
    "NSW",
    780000,
    2,
    1,
    1,
    "Apartment",
    "/Assets/ashfield/ashfield1.webp",
    ["/Assets/ashfield/ashfield2.avif", "/Assets/ashfield/ashfield3.avif"],
  ],
  [
    "buy",
    "200 Illawarra Rd",
    "Marrickville",
    "2204",
    "NSW",
    910000,
    3,
    2,
    1,
    "House",
    "/Assets/kogarah/kogarah1.webp",
    ["/Assets/kogarah/kogarah2.avif", "/Assets/kogarah/kogarah3.avif"],
  ],
  [
    "buy",
    "11 Smith St",
    "Chatswood",
    "2067",
    "NSW",
    1480000,
    4,
    2,
    2,
    "House",
    "/Assets/ryde/ryde1.webp",
    ["/Assets/ryde/ryde2.avif", "/Assets/ryde/ryde3.avif"],
  ],

  // --- Sold ---
  [
    "sold",
    "20 Crown St",
    "Wollongong",
    "2500",
    "NSW",
    650000,
    2,
    1,
    1,
    "Unit",
    "/Assets/parramatta/parramatta1.webp",
    ["/Assets/parramatta/parramatta2.avif", "/Assets/parramatta/parramatta3.webp"],
  ],
  [
    "sold",
    "88 George St",
    "Sydney",
    "2000",
    "NSW",
    1400000,
    3,
    2,
    1,
    "Apartment",
    "/Assets/ashfield/ashfield1.webp",
    ["/Assets/ashfield/ashfield2.avif", "/Assets/ashfield/ashfield3.avif"],
  ],
  [
    "sold",
    "34 King St",
    "Randwick",
    "2031",
    "NSW",
    1120000,
    3,
    2,
    1,
    "House",
    "/Assets/kogarah/kogarah1.webp",
    ["/Assets/kogarah/kogarah2.avif", "/Assets/kogarah/kogarah3.avif"],
  ],
  [
    "sold",
    "7 Queen St",
    "Ashfield",
    "2131",
    "NSW",
    780000,
    2,
    1,
    0,
    "Terrace",
    "/Assets/ashfield/ashfield1.webp",
    ["/Assets/ashfield/ashfield2.avif", "/Assets/ashfield/ashfield3.avif"],
  ],
  [
    "sold",
    "55 Oxford St",
    "Paddington",
    "2021",
    "NSW",
    1520000,
    3,
    2,
    1,
    "House",
    "/Assets/ryde/ryde1.webp",
    ["/Assets/ryde/ryde2.avif", "/Assets/ryde/ryde3.avif"],
  ],
  [
    "sold",
    "4 Bay St",
    "Double Bay",
    "2028",
    "NSW",
    1850000,
    4,
    3,
    2,
    "House",
    "/Assets/parramatta/parramatta1.webp",
    ["/Assets/parramatta/parramatta2.avif", "/Assets/parramatta/parramatta3.webp"],
  ],
  [
    "sold",
    "200 High St",
    "North Sydney",
    "2060",
    "NSW",
    1980000,
    4,
    2,
    2,
    "House",
    "/Assets/kogarah/kogarah1.webp",
    ["/Assets/kogarah/kogarah2.avif", "/Assets/kogarah/kogarah3.avif"],
  ],
  [
    "sold",
    "89 George St",
    "The Rocks",
    "2000",
    "NSW",
    2200000,
    5,
    3,
    2,
    "Penthouse",
    "/Assets/ryde/ryde1.webp",
    ["/Assets/ryde/ryde2.avif", "/Assets/ryde/ryde3.avif"],
  ],
  [
    "sold",
    "15 Marrickville Rd",
    "Marrickville",
    "2204",
    "NSW",
    870000,
    3,
    2,
    1,
    "House",
    "/Assets/ashfield/ashfield1.webp",
    ["/Assets/ashfield/ashfield2.avif", "/Assets/ashfield/ashfield3.avif"],
  ],
  [
    "sold",
    "76 Regent St",
    "Chippendale",
    "2008",
    "NSW",
    910000,
    3,
    2,
    1,
    "Terrace",
    "/Assets/kogarah/kogarah1.webp",
    ["/Assets/kogarah/kogarah2.avif", "/Assets/kogarah/kogarah3.avif"],
  ],
];

// ---- Use baseRows directly (all properties will be NSW)
const rows = baseRows;

db.serialize(() => {
  // 1) Clear old data
  db.run("DELETE FROM listings", [], (err) => {
    if (err) console.error("Error clearing listings:", err.message);
    else console.log("🗑️  Cleared listings table before seeding");
  });

  // 2) Insert fresh
  const stmt = db.prepare(`
    INSERT INTO listings
      (status,address,suburb,postcode,state,price,bedrooms,bathrooms,carspaces,type,image,images)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
  `);

  rows.forEach((r) => {
    const imagesJson = JSON.stringify(r[11] || []);
    stmt.run([...r.slice(0, 11), imagesJson]);
  });

  stmt.finalize((err) => {
    if (err) console.error("Seed insert failed:", err);
    else console.log(`✅ Inserted ${rows.length} listings (all NSW)`);
    process.exit(0);
  });
});
